import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile, rm, symlink, readdir } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { bootstrapRecords, playbookRead, playbookSearch, playbookStatus, playbookValidate, migrateRecords, rollbackRecordMigration } from '../src/records.mjs';
import { sha256, treeSnapshot } from '../src/fs-safety.mjs';
const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
async function fixture(t) {
  const target = await mkdtemp(path.join(os.tmpdir(), 'aapb-records-'));
  t.after(async () => { assert.equal(path.dirname(target), os.tmpdir()); await rm(target, { recursive: true, force: true }); });
  return target;
}
test('bootstrap creates one editable entrypoint, preserves policy, and is idempotent', async (t) => {
  const target = await fixture(t);
  await writeFile(path.join(target, 'AGENTS.md'), 'User policy\n');
  const before = await treeSnapshot(target);
  await bootstrapRecords({ target, repoRoot, dryRun: true });
  assert.deepEqual(await treeSnapshot(target), before);
  await bootstrapRecords({ target, repoRoot });
  const pb = path.join(target, '.ai-agent-playbook');
  assert.deepEqual((await readdir(pb)).sort(), ['.ai-agent-playbook-install.json', 'CURRENT.md', 'manifest.json']);
  await writeFile(path.join(pb, 'CURRENT.md'), '# Current\n\nUser content.\n');
  const current = await treeSnapshot(target);
  assert.equal((await bootstrapRecords({ target, repoRoot })).applied, false);
  assert.deepEqual(await treeSnapshot(target), current);
  assert.equal((await playbookValidate({ target })).ok, true);
  assert.equal(await readFile(path.join(target, 'AGENTS.md'), 'utf8'), 'User policy\n');
});
test('records are bounded, literal, non-mutating and retain source locations', async (t) => {
  const target = await fixture(t);
  await bootstrapRecords({ target, repoRoot });
  await writeFile(path.join(target, '.ai-agent-playbook/CURRENT.md'), '# State\nKeep API 0.5.11\n[x] is literal\n' + 'a'.repeat(1000));
  const before = await treeSnapshot(target);
  const read = await playbookRead({ target, startLine: 2, maxChars: 12 });
  assert.equal(read.content, 'Keep API 0.5');
  assert.equal(read.truncated, true);
  const search = await playbookSearch({ target, query: '[x]' });
  assert.equal(search.results[0].line, 3);
  assert.equal(search.results[0].path, 'CURRENT.md');
  assert.deepEqual(await treeSnapshot(target), before);
  await assert.rejects(playbookRead({ target, path: '../AGENTS.md' }), /Unsafe|relative/);
  await assert.rejects(playbookRead({ target, path: 'C:/private.md' }), /relative/);
  await assert.rejects(playbookRead({ target, path: 'CURRENT.md:stream' }), /relative/);
});
test('linked record directories cannot disclose data outside the bound project', async (t) => {
  const target = await fixture(t), outside = await fixture(t);
  await bootstrapRecords({ target, repoRoot });
  await writeFile(path.join(outside, 'private.md'), 'not a record');
  await symlink(outside, path.join(target, '.ai-agent-playbook/linked'), process.platform === 'win32' ? 'junction' : 'dir');
  await assert.rejects(playbookRead({ target, path: 'linked/private.md' }), /link|junction/);
  const search = await playbookSearch({ target, query: 'not a record' });
  assert.equal(search.results.length, 0);
  assert.ok(search.warnings.some((w) => w.includes('linked')));
});
test('legacy roots and ownership arrays remain readable; ambiguity is reported', async (t) => {
  const target = await fixture(t), pb = path.join(target, '.ai-playbook');
  await mkdir(pb);
  const body = '{"schemaVersion":"1","layoutKind":"structured"}\n';
  await writeFile(path.join(pb, 'CURRENT.md'), '# Kept legacy record\n');
  await writeFile(path.join(pb, 'manifest.json'), body);
  await writeFile(path.join(pb, '.ai-agent-playbook-install.json'), JSON.stringify({ source: 'ai-agent-playbook', schemaVersion: '1', files: [{ path: '.ai-playbook/manifest.json', sourceHash: sha256(body) }] }));
  assert.equal((await playbookStatus({ target })).layout, 'structured');
  assert.equal((await playbookValidate({ target })).ok, true);
  assert.match((await playbookRead({ target })).content, /Kept legacy/);
  await mkdir(path.join(target, '.ai-agent-playbook'));
  await assert.rejects(playbookStatus({ target }), /Multiple/);
});
test('layout migration preserves documents and supports checked rollback and replay', async (t) => {
  const target = await fixture(t);
  await bootstrapRecords({ target, repoRoot });
  const pb = path.join(target, '.ai-agent-playbook'), body = '{"schemaVersion":"1","layoutKind":"structured"}\n';
  await writeFile(path.join(pb, 'manifest.json'), body);
  await writeFile(path.join(pb, '.ai-agent-playbook-install.json'), JSON.stringify({ schemaVersion: 1, source: 'ai-agent-playbook', files: [{ path: '.ai-agent-playbook/manifest.json', sourceHash: sha256(body) }] }));
  await writeFile(path.join(pb, 'CURRENT.md'), '# Reviewed\nDo not change API.\n');
  const before = await treeSnapshot(target);
  await migrateRecords({ target });
  assert.deepEqual(await treeSnapshot(target), before);
  assert.equal((await migrateRecords({ target, apply: true })).applied, true);
  assert.equal((await migrateRecords({ target, apply: true })).applied, false);
  assert.equal(await readFile(path.join(pb, 'CURRENT.md'), 'utf8'), '# Reviewed\nDo not change API.\n');
  const backup = 'archive/' + (await readdir(path.join(pb, 'archive')))[0];
  assert.equal((await rollbackRecordMigration({ target, backup })).applied, false);
  assert.equal((await rollbackRecordMigration({ target, backup, apply: true })).applied, true);
  assert.equal(await readFile(path.join(pb, 'manifest.json'), 'utf8'), body);
  assert.equal((await rollbackRecordMigration({ target, backup, apply: true })).applied, false);
});
test('unmanaged layout and later metadata edits are never overwritten', async (t) => {
  const target = await fixture(t);
  await bootstrapRecords({ target, repoRoot });
  const pb = path.join(target, '.ai-agent-playbook');
  await writeFile(path.join(pb, 'manifest.json'), '{"layoutKind":"custom"}\n');
  const before = await treeSnapshot(target);
  const result = await migrateRecords({ target, apply: true });
  assert.equal(result.ok, false);
  assert.equal(result.applied, false);
  assert.deepEqual(await treeSnapshot(target), before);
});
